apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openbank-transfers.fullname" . }}-config
  labels:
    app: {{ include "openbank-transfers.name" . }}
data:
  APP_APP_ENV: {{ .Values.env.APP_APP_ENV | quote }}