{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "swiftpay.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swiftpay.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      {{- include "swiftpay.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      honorLabels: true
{{- end }}