server:
  port: 8080

spring:
  application:
    name: gpp-backend
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/YOUR_GCP_PROJECT_ID
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

app:
  cors:
    allowed-origins: ["https://your-frontend-domain"]