apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - payments.example.com
      secretName: gpp-tls
  rules:
    - host: payments.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gpp-backend
                port:
                  number: 8443